imports:
  - path: github.com/hugomods/icons
  - path: github.com/hugomods/icons/vendors/bootstrap
  - path: github.com/hugomods/icons/vendors/feather
  - path: github.com/hugomods/icons/vendors/font-awesome
  - path: github.com/hugomods/icons/vendors/lucide
  - path: github.com/hugomods/icons/vendors/mdi
  - path: github.com/hugomods/icons/vendors/simple-icons
  - path: github.com/hugomods/icons/vendors/tabler
  - path: github.com/hbstack/meta/recommended
  - path: github.com/hbstack/header/modules/banner
  - path: github.com/hugomods/aos
  - path: github.com/hugomods/video-js
  - path: github.com/hugomods/katex
  - path: github.com/hugomods/mermaid
  - path: github.com/hugomods/google-analytics
  - path: github.com/hugomods/seo/modules/favicons
