imports:
  - path: github.com/hugomods/icons
  - path: github.com/hbstack/meta/recommended
  - path: github.com/hbstack/header/modules/banner
  - path: github.com/hugomods/aos
  - path: github.com/hugomods/video-js
  # - path: github.com/hugomods/site/common
