bootstrap:
  config_toggle:
    langs:
      - yaml
      - toml
      - json

mermaid:
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hb:
  css_bundle_name: ls
  debug: false
  js_bundle_name: ls
  logo: images/logo-square-2.png
  blog:
    home:
      recent_posts: 12
      main_sections:
        - blog
        - software-engineering
        - programming
        - oop
      # taxonomies: true
    sidebar:
      taxonomies:
        style: underline

  # blog:
    # archives:
    #   paginate: 30
    # paginate: 12
    # post_date_format: :date_short
    # post_thumbnail: true
    # post_thumbnail_default: images/thumbnail.png
    # post_thumbnail_placeholder: ""

seo:
  favicons:
    icon: images/logo-square-2.png
    sizes:
      - size: 16x16
      - size: 32x32
      - size: 150x150
      - rel: apple-touch-icon
        size: 180x180
      - size: 192x192

aos:
  css_url: https://unpkg.com/aos@next/dist/aos.css
  js_url: https://unpkg.com/aos@next/dist/aos.js
