# copyright:
#   authors: [Learn-Software.com](https://learn-software.com/). Todos los derechos reservados.
#   from_year: 2022

ui:
  feedback:
    enable: true
    'yes': >-
      ¡Nos alegra mucho! Por favor <a href="https://github.com/learn-software-engineering/learn-software-engineering/issues/new">dinos como podemos mejorar</a>.
    'no': >-
      Nos apena que no te haya gustado. Por favor <a href="https://github.com/learn-software-engineering/learn-software-engineering/issues/new">dinos como podemos mejorar</a>.
