hb:
  header:
    socials:
      github: learn-software-engineering
      gmail: mailto://learn.software.eng@gmail.com
      linkedin: https://linkedin.com/company/learn-software
      twitter: https://twitter.com/software45687
      youtube: https://www.youtube.com/@aprende-software
  footer:
    socials:
      github: learn-software-engineering
      gmail: mailto://learn.software.eng@gmail.com
      linkedin: https://linkedin.com/company/learn-software
      twitter: https://twitter.com/software45687
      youtube: https://www.youtube.com/@aprende-software
