hb:
  css_bundle_name: ls
  debug: false
  js_bundle_name: ls
  logo: images/logo-square-1.jpeg

  blog:
    archives:
      paginate: 30
    full_width: false
    home:
      featured_posts: 5
      main_sections:
      - docs
      - blog
      taxonomies: true
    paginate: 12
    post_date_format: :date_short
    post_thumbnail: true
    post_thumbnail_default: images/thumbnail.png
    post_thumbnail_placeholder: ""
