hb:
  header:
    socials:
      youtube: https://www.youtube.com/@aprende-software
      github: learn-software-engineering
      linkedin: https://linkedin.com/company/learn-software
      twitter: https://twitter.com/software45687
  footer:
    socials:
      youtube: https://www.youtube.com/@aprende-software
      github: learn-software-engineering
      linkedin: https://linkedin.com/company/learn-software
      twitter: https://twitter.com/software45687
