ui:
  showLightDarkModeMenu: true
  breadcrumb_disable: false
  taxonomy_breadcrumb_disable: true

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id: 775596d046f8749af

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo: https://github.com/learn-software-engineering/learn-software-engineering

katex:
  enable: true

GitInfo: true

# links:
#   # End user relevant links. These will show up on left side of footer and in the community page if you have one.
#   user:
#     - name: User mailing list
#       url: https://example.org/mail
#       icon: fa fa-envelope
#       desc: Discussion and help from your fellow users
#     - name: Twitter
#       url: https://example.org/twitter
#       icon: fab fa-twitter
#       desc: Follow us on Twitter to get the latest news!
#     - name: Stack Overflow
#       url: https://example.org/stack
#       icon: fab fa-stack-overflow
#       desc: Practical questions and curated answers
#   # Developer relevant links. These will show up on right side of footer and in the community page if you have one.
#   developer:
#     - name: GitHub
#       url: https://github.com/google/docsy
#       icon: fab fa-github
#       desc: Development takes place here!
#     - name: Slack
#       url: https://example.org/slack
#       icon: fab fa-slack
#       desc: Chat with other project developers
#     - name: Developer mailing list
#       url: https://example.org/mail
#       icon: fa fa-envelope
#       desc: Discuss development issues around the project
