# copyright:
#   authors: [Learn-Software.com](https://learn-software.com/). All Rights Reserved.
#   from_year: 2022

ui:
  feedback:
    enable: true
    'yes': >-
      Glad to hear it! Please <a href="https://github.com/learn-software-engineering/learn-software-engineering/issues/new">tell us how we can improve</a>.
    'no': >-
      Sorry to hear that. Please <a href="https://github.com/learn-software-engineering/learn-software-engineering/issues/new">tell us how we can improve</a>.
