ui:
  showLightDarkModeMenu: true
  breadcrumb_disable: false
  taxonomy_breadcrumb_disable: true
  sidebar_menu_compact: true
  sidebar_search_disable: true

# Google Custom Search Engine ID. Remove or comment out to disable GCSE search.
# gcs_engine_id: 775596d046f8749af

# Local search with Lunr
offlineSearch: true
offlineSearchMaxResults: 25

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo: https://github.com/learn-software-engineering/learn-software-engineering

katex:
  enable: true

GitInfo: true

rss_sections: [blog]

# links:
#   # End user relevant links. These will show up on left side of footer and in the community page if you have one.
#   user:
#     - name: Contact us via email
#       url: mailto://learn.software.eng@gmail.com
#       icon: fa fa-envelope
#       # fa-solid fa-square-envelope
#     - name: Twitter
#       url: https://example.org/twitter
#       icon: fab fa-twitter
#       desc: Follow us on X!
#   # Developer relevant links. These will show up on right side of footer and in the community page if you have one.
#   developer:
#     - name: GitHub
#       url: https://github.com/google/docsy
#       icon: fab fa-github
#       desc: Development takes place here!
#     - name: Slack
#       url: https://example.org/slack
#       icon: fab fa-slack
#       desc: Chat with other project developers
#     - name: Developer mailing list
#       url: https://example.org/mail
#       icon: fa fa-envelope
#       desc: Discuss development issues around the project


  # header:
  #   socials:
  #     facebook: https://www.facebook.com/learn.software.eng
  #     github: learn-software-engineering
  #     gmail:
  #     instagram: https://www.instagram.com/learnsoftwareeng
  #     linkedin: https://linkedin.com/company/learn-software
  #     patreon: https://patreon.com/learnsoftwareeng
  #     twitter: https://twitter.com/software45687
  #     youtube: https://www.youtube.com/@learn-software
  # footer:
  #   socials:
  #     facebook: https://www.facebook.com/learn.software.eng
  #     github: learn-software-engineering
  #     gmail: mailto://learn.software.eng@gmail.com
  #     instagram: https://www.instagram.com/learnsoftwareeng
  #     linkedin: https://linkedin.com/company/learn-software
  #     patreon: https://patreon.com/learnsoftwareeng
  #     twitter: https://twitter.com/software45687
  #     youtube: https://www.youtube.com/@learn-software
