name: PR Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  english-cspell-md-files:
    runs-on: ubuntu-latest
    container: ghcr.io/cn-writing/cspell:6.12.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: CSpell English
        run: cspell --config .github/workflows/scripts/cspell-config-en.json "content/en/**/*.md"
  # spanish-cspell-md-files:
  #   runs-on: ubuntu-latest
  #   container: ghcr.io/cn-writing/cspell:6.12.0
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: CSpell Spanish
  #       run: cspell --config .github/workflows/scripts/cspell-config-es.json "content/es/**/*.md"
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/cn-writing/hugo
    env:
      ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: npm install
      - name: Build with Hugo
        run: .github/workflows/scripts/build.sh
