name: PR Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  english-cspell-md-files:
    runs-on: ubuntu-latest
    container: ghcr.io/cn-writing/cspell:8.17.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: CSpell
        run: make spell-check
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/cn-writing/hugo
    env:
      ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: npm install
      - name: Build with Hugo
        run: .github/workflows/scripts/build.sh
